# Generated by Django 4.0.5 on 2022-06-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmuyg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birim',
            old_name='kg',
            new_name='birim',
        ),
        migrations.RenameField(
            model_name='birimfiyat',
            old_name='birim_fiyat',
            new_name='birim',
        ),
        migrations.RemoveField(
            model_name='birim',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='birim',
            name='m3',
        ),
        migrations.RemoveField(
            model_name='birim',
            name='mt',
        ),
    ]
