# Generated by Django 4.0.5 on 2022-06-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmuyg', '0002_rename_kg_birim_birim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birimfiyat',
            name='birim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmuyg.birim'),
        ),
    ]
